name = "learn_gleam_todo"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 2.1.1 and < 3.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
youid = ">= 1.5.1 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
pog = ">= 4.1.0 and < 5.0.0"
lustre = ">= 5.4.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 4.6.0 and < 5.0.0"
